import { createCheckRun, updateCheckRun, CheckRunOutput } from '../lib/github';
import { githubApp } from '../lib/github';

async function main() {
    console.log('--- Check Runs API Test ---\n');

    // 1. Get Installation & Latest Commit SHA
    let installationId: number | undefined;
    let headSha: string | undefined;
    const owner = 'jamitechnologies';
    const repo = 'picklet';

    try {
        const installations = await githubApp.octokit.rest.apps.listInstallations();
        if (installations.data.length > 0) {
            installationId = installations.data[0].id;
            console.log(`✅ Using Installation ID: ${installationId}`);
        }
    } catch (e: any) {
        console.error('❌ Failed to list installations:', e.message);
        return;
    }

    if (!installationId) return;

    // Fetch latest commit SHA from main/master
    // We can use the simple git client or just octokit
    const octokit = await githubApp.getInstallationOctokit(installationId);
    try {
        const { data: ref } = await octokit.rest.git.getRef({
            owner,
            repo,
            ref: 'heads/main'
        });
        headSha = ref.object.sha;
        console.log(`✅ Using Head SHA: ${headSha}`);
    } catch (e: any) {
        console.log('Could not get main branch ref, trying master');
        try {
            const { data: ref } = await octokit.rest.git.getRef({
                owner,
                repo,
                ref: 'heads/master'
            });
            headSha = ref.object.sha;
            console.log(`✅ Using Head SHA: ${headSha}`);
        } catch (e2) {
            console.error('❌ Failed to get head SHA');
            return;
        }
    }

    if (!headSha) return;

    // 2. Create Check Run (Queued)
    console.log('Creating Check Run...');
    const runId = await createCheckRun(installationId, owner, repo, headSha, 'API Test Run');
    console.log(`✅ Created Check Run ID: ${runId} (Status: queued)`);
    console.log('   Check the GitHub UI "Checks" tab now.');

    await new Promise(r => setTimeout(r, 2000));

    // 3. Update to In Progress
    console.log('Updating to In Progress...');
    await updateCheckRun(installationId, owner, repo, runId, 'in_progress');
    console.log(`✅ Updated Status: in_progress`);

    await new Promise(r => setTimeout(r, 2000));

    // 4. Complete
    console.log('Completing Run...');
    const output: CheckRunOutput = {
        title: 'Test Complete',
        summary: 'This was a test run generated by the API client.',
        text: 'Detailed report content here.\n- Item 1\n- Item 2',
        annotations: [
            {
                path: 'README.md',
                start_line: 1,
                end_line: 1,
                annotation_level: 'notice',
                message: 'This is the title of the readme',
                title: 'Readme Check'
            }
        ]
    };

    await updateCheckRun(installationId, owner, repo, runId, 'completed', 'success', output);
    console.log(`✅ Completed Status: success`);
    console.log('   Check GitHub UI for annotations.');
}

main();
