CREATE TABLE IF NOT EXISTS schema_checks (
    id SERIAL PRIMARY KEY,
    repo_name VARCHAR(255) NOT NULL,
    pr_number INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
